// Accent color presets for the panel's theme picker.
// Colors are applied at runtime as CSS variables (--primary, --primary-dark, --accent)
// so all shared components (buttons, inputs, badges, glows) follow the chosen accent.
export const ACCENT_PRESETS = [
  {
    key: 'indigo',
    label: { fa: 'آبی الکترونیکی', en: 'Electric Indigo' },
    desc: { fa: 'تیره و حرفه‌ای', en: 'Dark & professional' },
    primary: '#6366f1',
    primaryDark: '#4f46e5',
    accent: '#8b5cf6',
    group: 'dark',
  },
  {
    key: 'emerald',
    label: { fa: 'زمرد سبز', en: 'Emerald Green' },
    desc: { fa: 'خنک و اطمینان‌بخش', en: 'Cool & confident' },
    primary: '#10b981',
    primaryDark: '#059669',
    accent: '#34d399',
    group: 'dark',
  },
  {
    key: 'violet',
    label: { fa: 'بنفش رویا', en: 'Dream Violet' },
    desc: { fa: 'خلاقانه و لوکس', en: 'Creative & luxe' },
    primary: '#8b5cf6',
    primaryDark: '#7c3aed',
    accent: '#a78bfa',
    group: 'dark',
  },
  {
    key: 'amber',
    label: { fa: 'غروب گرم', en: 'Warm Sunset' },
    desc: { fa: 'گرم و پرانرژی', en: 'Warm & energetic' },
    primary: '#f59e0b',
    primaryDark: '#d97706',
    accent: '#fb923c',
    group: 'dark',
  },
  {
    key: 'rose',
    label: { fa: 'گلبهی رز', en: 'Rose' },
    desc: { fa: 'ملایم و شیک', en: 'Soft & elegant' },
    primary: '#ec4899',
    primaryDark: '#db2777',
    accent: '#f472b6',
    group: 'dark',
  },
  {
    key: 'slate',
    label: { fa: 'مشکی خاص', en: 'Midnight Slate' },
    desc: { fa: 'مینیمال و خاص', en: 'Minimal & sleek' },
    primary: '#64748b',
    primaryDark: '#475569',
    accent: '#94a3b8',
    group: 'dark',
  },
  {
    key: 'cyan',
    label: { fa: 'دریای آبی', en: 'Ocean Blue' },
    desc: { fa: 'روشن و آرام', en: 'Bright & calm' },
    primary: '#06b6d4',
    primaryDark: '#0891b2',
    accent: '#22d3ee',
    group: 'light',
  },
  {
    key: 'cream',
    label: { fa: 'کاغذ کرم', en: 'Cream Paper' },
    desc: { fa: 'گرم و کاغذی', en: 'Warm & paper-like' },
    primary: '#d97706',
    primaryDark: '#b45309',
    accent: '#fbbf24',
    group: 'light',
  },
  {
    key: 'lavender',
    label: { fa: 'اسطوخودوس', en: 'Lavender' },
    desc: { fa: 'ملایم و آرامش‌بخش', en: 'Soft & relaxing' },
    primary: '#a78bfa',
    primaryDark: '#8b5cf6',
    accent: '#c4b5fd',
    group: 'light',
  },
  {
    key: 'mint',
    label: { fa: 'نعناع سبز', en: 'Fresh Mint' },
    desc: { fa: 'تازه و شاداب', en: 'Fresh & lively' },
    primary: '#2dd4bf',
    primaryDark: '#14b8a6',
    accent: '#5eead4',
    group: 'light',
  },
  {
    key: 'neon',
    label: { fa: 'نئون', en: 'Neon' },
    desc: { fa: 'سایبری و پرانرژی', en: 'Cyber & energetic' },
    primary: '#22d3ee',
    primaryDark: '#06b6d4',
    accent: '#a3e635',
    group: 'dark',
  },
  {
    key: 'graphite',
    label: { fa: 'مینیمال خاکستری', en: 'Minimal Graphite' },
    desc: { fa: 'ساده و بی‌حاشیه', en: 'Clean & minimal' },
    primary: '#94a3b8',
    primaryDark: '#64748b',
    accent: '#cbd5e1',
    group: 'dark',
  },
]

export const DEFAULT_ACCENT = 'indigo'
